#declare textureBrick  = pigment { image_map { jpeg "img/textures/Brick.jpg"      } scale 1000 }
#declare textureBrick2 = pigment { image_map { jpeg "img/textures/Brick2.jpg"     } scale 1000 }
#declare textureBrick3 = pigment { image_map { jpeg "img/textures/Brick_myst.jpg" } scale 1000 }
#declare textureLog    = pigment { image_map { jpeg "img/textures/log.jpg"        } }
#declare textureTrunk  = pigment { image_map { jpeg "img/textures/trunk.jpg"      } }